apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      imagePullSecrets:          
        - name: registry-credentials
      containers:
        - name: juiceshop
          image: registry.local:5443/juiceshop@sha256:683633b20c4f0bea6d97853ab9e563a7f8ce6c2ff9acb7472dcca1be7860f8e0
          ports:
            - containerPort: 3000
