apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      imagePullSecrets:          
        - name: registry-credentials
      containers:
        - name: juiceshop
          image: registry.local:5443/juiceshop@sha256:f9416eadc2cf0c8f6b5468a936150ef1e22cc32a3697f8ec675c8f7bed9d35dd
          ports:
            - containerPort: 3000
