apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      imagePullSecrets:          # ← au même niveau que containers
        - name: registry-credentials
      containers:
        - name: juiceshop
          image: registry.local:5443/juiceshop@sha256:fab071dbc8688bfd31af58b3533a9ccec118e0f27df0f172c6e82fdad22c3ef7
          ports:
            - containerPort: 3000
